apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-services-deployment
  labels:
    app: kafka-services
    version: v1
spec:
  selector:
    matchLabels:
      app: kafka-services
      version: v1
  template:
    metadata:
      labels:
        app: kafka-services
        version: v1
    spec:
      containers:
      - name: kafka-services
        image: strimzi/kafka:0.20.1-kafka-2.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        - containerPort: 29092
        securityContext:
          privileged: true
          capabilities:
            add:
              - ALL
        env:
          - name: LOG_DIR
            value: "/tmp/logs"
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeper-services.default.svc.cluster.local:2181"
          - name: KAFKA_LISTENERS
            value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INTERNAL://kafka-services.default.svc.cluster.local:29092,EXTERNAL://localhost:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INTERNAL"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
        command:
        - sh
        - -c
        - "bin/kafka-server-start.sh config/server.properties --override inter.broker.listener.name=$KAFKA_INTER_BROKER_LISTENER_NAME --override listener.security.protocol.map=$KAFKA_LISTENER_SECURITY_PROTOCOL_MAP --override listeners=$KAFKA_LISTENERS --override advertised.listeners=$KAFKA_ADVERTISED_LISTENERS --override zookeeper.connect=$KAFKA_ZOOKEEPER_CONNECT"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-services
spec:
  selector:
    app: kafka-services
  ports:
  - port: 9092
    targetPort: 9092
    name: http
    protocol: TCP
  - port: 29092
    targetPort: 29092
    name: kafka
    protocol: TCP
  type: LoadBalancer
