apiVersion: apps/v1
kind: Deployment
metadata:
  name: travels-services-deployment
  labels:
    app: travels-console-services
    version: v1
spec:
  selector:
    matchLabels:
      app: travels-console-services
      version: v1
  template:
    metadata:
      labels:
        app: travels-console-services
        version: v1
    spec:
      containers:
      - name: travels-console-services
        image: containersoga/travels
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
          capabilities:
            add:
              - ALL
        env:
          - name: EXTERNAL_TRAVELS_HOST
            value: "http://localhost:8080"
          - name: EXTERNAL_DATAINDEX_HOST_HTTP
            value: "http://localhost:8180"
          - name: EXTERNAL_DATAINDEX_HOST_WS
            value: "ws://localhost:8180"
          - name: EXTERNAL_HOST_KEYCLOAK
            value: "http://localhost:8480"
          - name: INTERNAL_INFINISPAN_HOST
            value: "infinispan-services.default.svc.cluster.local:11222"
          - name: INTERNAL_KAFKA_HOST
            value: "kafka-services.default.svc.cluster.local:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: travels-console-services
spec:
  selector:
    app: travels-console-services
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  type: LoadBalancer
