apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeper-services-deployment
  labels:
    app: zookeper-services
    version: v1
spec:
  selector:
    matchLabels:
      app: zookeper-services
      version: v1
  template:
    metadata:
      labels:
        app: zookeper-services
        version: v1
    spec:
      containers:
      - name: zookeper-services
        image: strimzi/kafka:0.20.1-kafka-2.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        securityContext:
          privileged: true
          capabilities:
            add:
              - ALL
        env:
          - name: LOG_DIR
            value: "/tmp/logs"
        command:
        - sh
        - -c
        - "bin/zookeeper-server-start.sh config/zookeeper.properties"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeper-services
spec:
  selector:
    app: zookeper-services
  ports:
  - port: 2181
    targetPort: 2181
    name: http
    protocol: TCP
  type: LoadBalancer
